apiVersion: v2
name: devpro-salesportal
description: Helm chart for Devpro Sales Portal
type: application
version: 0.2.8
appVersion: "1.1.18203306613"
dependencies:
  - name: mongodb
    version: 18.1.10   # MongoDB 8.2.2
    repository: https://charts.bitnami.com/bitnami
    alias: mongodb
    condition: mongodb.enabled
maintainers:
  - name: devpro
    email: bertrand@devpro.fr
