front:
  enabled: true
  host: sales-portal.random
  name: salesportal-wasmapp
  image: docker.io/devprofr/salesportal-wasmapp
  # images are hosted on DockerHub: https://hub.docker.com/r/devprofr/salesportal-wasmapp/tags
  tag: latest             # IMPORTANT: latest should never be used in Production
  port: 80
  replicaCount: 1
  healthEndpoint: /health
  db: {}
  extraEnv: []
    # - name: xxx
    #   value: "yyyy"
  additionalPodLabels: {}
  tls:
    secretName: sales-portal-tls
  resources: {}
    # limits:
    #   cpu: 200m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 64Mi

adapter:
  enabled: true
  host: crm-adapter.random
  name: salesportal-crmadapterwebapi
  image: docker.io/devprofr/salesportal-crmadapterwebapi
  # images are hosted on DockerHub: https://hub.docker.com/r/devprofr/salesportal-crmadapterwebapi/tags
  tag: latest             # IMPORTANT: latest should never be used in Production
  replicaCount: 1
  port: 8080
  healthEndpoint: /health
  db: {}
  extraEnv: []
  additionalPodLabels: {}
  tls:
    secretName: crm-adapter-tls
  resources: {}

data:
  enabled: true
  host: crm-data.random
  name: salesportal-crmdatawebapi
  image: docker.io/devprofr/salesportal-crmdatawebapi
  # images are hosted on DockerHub: https://hub.docker.com/r/devprofr/salesportal-crmdatawebapi/tags
  tag: latest             # IMPORTANT: latest should never be used in Production
  replicaCount: 1
  port: 8080
  healthEndpoint: /health
  db:
    connectionString: "someconnstring"
    databaseName: "somedb"
  extraEnv: []
  additionalPodLabels: {}
  tls:
    secretName: crm-data-tls
  resources: {}

dotnet:
  environment: Production
  logLevels:
    default: Information
    framework: Information
    application: Information
  enableSwagger: false
  enableOpenTelemetry: false
  skipCertificateValidation: false

ingress:
  enabled: false
  className: ""
  annotations: {}
    # cert-manager.io/cluster-issuer: letsencrypt-prod

# embedded chart configuration: https://github.com/bitnami/charts/blob/main/bitnami/mongodb/values.yaml
mongodb:
  enabled: false
  global:
  #   imageRegistry: ""
  #   imagePullSecrets: []
  #   defaultStorageClass: ""
  #   storageClass: ""
    security:
      allowInsecureImages: true
  image:
    registry: docker.io
    repository: bitnami/mongodb     # other options: chainguard/mongodb
    tag: latest                     # IMPORTANT: latest should never be used in Production
  auth: {}
    # rootPassword: ""
