apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Release.Namespace }}-limits
  namespace: {{ .Release.Namespace }}
spec:
  limits:
    - type: Container
      default:
        cpu: {{ .Values.defaultLimitCpu }}
        memory: {{ .Values.defaultLimitMemory }}
      defaultRequest:
        cpu: {{ .Values.defaultRequestCpu }}
        memory: {{ .Values.defaultRequestMemory }}
      max:
        cpu: {{ .Values.maxCpu }}
        memory: {{ .Values.maxMemory }}
