apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.jobName }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Values.jobName }}
              image: {{ .Values.image }}
              command:
                {{- range .Values.command }}
                - {{ . | quote }}
                {{- end }}
              resources:
                requests:
                  cpu: {{ .Values.requestCpu }}
                  memory: {{ .Values.requestMemory }}
                limits:
                  cpu: {{ .Values.limitCpu }}
                  memory: {{ .Values.limitMemory }}
          restartPolicy: {{ .Values.restartPolicy }}
