apiVersion: v1
kind: Namespace
metadata:
  name: platform-system
  labels:
    managed-by: plural-gitops
    environment: shared

# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: monitoring
#   labels:
#     managed-by: plural-gitops
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: logging
#   labels:
#     managed-by: plural-gitops