{{- if $.Values.defaults.resourceQuota.enabled }}
{{- range .Values.namespaces }}
{{- $quota := $.Values.defaults.resourceQuota }}
{{- $nsQuota := .resourceQuota | default dict }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .name }}-quota
  namespace: {{ .name }}
spec:
  hard:
    requests.cpu: {{ ($nsQuota.requests).cpu | default $quota.requests.cpu | quote }}
    requests.memory: {{ ($nsQuota.requests).memory | default $quota.requests.memory | quote }}
    limits.cpu: {{ ($nsQuota.limits).cpu | default $quota.limits.cpu | quote }}
    limits.memory: {{ ($nsQuota.limits).memory | default $quota.limits.memory | quote }}
    pods: {{ $nsQuota.pods | default $quota.pods | quote }}
{{- end }}
{{- end }}
