{{- if .Values.limitRange.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.namespace.name }}-limits
  namespace: {{ .Values.namespace.name }}
spec:
  limits:
    - default:
        cpu: {{ .Values.limitRange.defaultLimit.cpu }}
        memory: {{ .Values.limitRange.defaultLimit.memory }}
      defaultRequest:
        cpu: {{ .Values.limitRange.defaultRequest.cpu }}
        memory: {{ .Values.limitRange.defaultRequest.memory }}
      type: Container
{{- end }}
