apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.targetApp }}-pdb
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.minAvailable }}
  minAvailable: {{ .Values.minAvailable }}
  {{- end }}
  {{- if .Values.maxUnavailable }}
  maxUnavailable: {{ .Values.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.targetApp }}
