{{- range .Values.quotas }}
{{- if (.demoPod).enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .namespace }}-demo-app
  namespace: {{ .namespace }}
  labels:
    app: demo-app
spec:
  replicas: {{ .demoPod.replicas }}
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo
          image: {{ .demoPod.image }}
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: {{ .demoPod.requestCpu }}
              memory: {{ .demoPod.requestMemory }}
            limits:
              cpu: {{ .demoPod.limitCpu }}
              memory: {{ .demoPod.limitMemory }}
{{- end }}
{{- end }}
