apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Release.Namespace }}-quota
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    requests.cpu: {{ .Values.requests.cpu | quote }}
    requests.memory: {{ .Values.requests.memory | quote }}
    limits.cpu: {{ .Values.limits.cpu | quote }}
    limits.memory: {{ .Values.limits.memory | quote }}
    pods: {{ .Values.pods | quote }}
