{{- range .Values.quotas }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .namespace }}-quota
  namespace: {{ .namespace }}
spec:
  hard:
    requests.cpu: {{ .requests.cpu | quote }}
    requests.memory: {{ .requests.memory | quote }}
    limits.cpu: {{ .limits.cpu | quote }}
    limits.memory: {{ .limits.memory | quote }}
    pods: {{ .pods | quote }}
{{- end }}
